import { Laptop } from "./app/shared/models/laptop";

export const sample_laptops: Laptop[] = [
    {
        id: 1,
        name: 'Acer Extensa',
        price: 500,
        cookTime: '10-15',
        favorite: true,
        origins: ['germany', ' us'],
        stars: 3.5,
        imageUrl: '/assets/images/acer.jpg',
        tags: ['laptop', 'acer'],
      },
      {
        id: 2,
        name: 'Asus 15',
        price: 600,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', ' us'],
        stars: 3.5,
        imageUrl: '/assets/images/asus.jpg',
        tags: ['laptop', 'asus'],
      },
      {
        id: 3,
        name: 'Asus X515KA',
        price: 700,
        cookTime: '10-15',
        favorite: true,
        origins: ['germany', ' us'],
        stars: 3.5,
        imageUrl: '/assets/images/asus2.jpg',
        tags: ['laptop', 'acer'],
      },
      {
        id: 4,
        name: 'JPGroup Classmate Leap W301',
        price: 500,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', ' us'],
        stars: 3.5,
        imageUrl: '/assets/images/black.jpg',
        tags: ['laptop', 'acer'],
      },
      {
        id: 5,
        name: 'HP 250',
        price: 700,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', ' us'],
        stars: 3.5,
        imageUrl: '/assets/images/hp.jpg',
        tags: ['laptop', 'acer'],
      },
      {
        id: 6,
        name: ' Lenovo V15 G2',
        price: 500,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', ' us'],
        stars: 3.5,
        imageUrl: '/assets/images/lenovo.jpg',
        tags: ['laptop', 'acer'],
      },
]